//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelServiceSys.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabelServiceSys.Resources.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Branch number log table 的本地化字符串。
        /// </summary>
        public static string Default_Html_btnOperationLog_Hawb {
            get {
                return ResourceManager.GetString("Default_Html_btnOperationLog_Hawb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bag number log table 的本地化字符串。
        /// </summary>
        public static string Default_Html_btnOperationLog_HU {
            get {
                return ResourceManager.GetString("Default_Html_btnOperationLog_HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login or Logout table 的本地化字符串。
        /// </summary>
        public static string Default_Html_btnOperationLog_Login {
            get {
                return ResourceManager.GetString("Default_Html_btnOperationLog_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other log table 的本地化字符串。
        /// </summary>
        public static string Default_Html_btnOperationLog_Other {
            get {
                return ResourceManager.GetString("Default_Html_btnOperationLog_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Part No. log table 的本地化字符串。
        /// </summary>
        public static string Default_Html_btnOperationLog_Pcid {
            get {
                return ResourceManager.GetString("Default_Html_btnOperationLog_Pcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user information management 的本地化字符串。
        /// </summary>
        public static string Default_Html_btnUserManagement {
            get {
                return ResourceManager.GetString("Default_Html_btnUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current user 的本地化字符串。
        /// </summary>
        public static string Default_Html_CurrentUser {
            get {
                return ResourceManager.GetString("Default_Html_CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        public static string Default_Html_Exit {
            get {
                return ResourceManager.GetString("Default_Html_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workstation 的本地化字符串。
        /// </summary>
        public static string Default_Html_LeftNavigation_Title {
            get {
                return ResourceManager.GetString("Default_Html_LeftNavigation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Default_Html_mm_exit {
            get {
                return ResourceManager.GetString("Default_Html_mm_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Default_Html_mm_tabclose {
            get {
                return ResourceManager.GetString("Default_Html_mm_tabclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close all 的本地化字符串。
        /// </summary>
        public static string Default_Html_mm_tabcloseall {
            get {
                return ResourceManager.GetString("Default_Html_mm_tabcloseall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current page left all off 的本地化字符串。
        /// </summary>
        public static string Default_Html_mm_tabcloseleft {
            get {
                return ResourceManager.GetString("Default_Html_mm_tabcloseleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close other 的本地化字符串。
        /// </summary>
        public static string Default_Html_mm_tabcloseother {
            get {
                return ResourceManager.GetString("Default_Html_mm_tabcloseother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current page right all off 的本地化字符串。
        /// </summary>
        public static string Default_Html_mm_tabcloseright {
            get {
                return ResourceManager.GetString("Default_Html_mm_tabcloseright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refeash 的本地化字符串。
        /// </summary>
        public static string Default_Html_mm_tabupdate {
            get {
                return ResourceManager.GetString("Default_Html_mm_tabupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guide of user 的本地化字符串。
        /// </summary>
        public static string Default_Html_tab_Content_1 {
            get {
                return ResourceManager.GetString("Default_Html_tab_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performance appraisal system 的本地化字符串。
        /// </summary>
        public static string Default_Html_Title {
            get {
                return ResourceManager.GetString("Default_Html_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guide of user 的本地化字符串。
        /// </summary>
        public static string Default_JS_defaultTabTitle {
            get {
                return ResourceManager.GetString("Default_JS_defaultTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The cause of the error 的本地化字符串。
        /// </summary>
        public static string Error_Html_Label1 {
            get {
                return ResourceManager.GetString("Error_Html_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Returns the login page 的本地化字符串。
        /// </summary>
        public static string Error_Html_Label2 {
            get {
                return ResourceManager.GetString("Error_Html_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong!!! 的本地化字符串。
        /// </summary>
        public static string Error_Html_Title {
            get {
                return ResourceManager.GetString("Error_Html_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The device type is not specified 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_ErrorMessage1 {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not specify whether DVIR 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_ErrorMessage2 {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user name not specified 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_ErrorMessage3 {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unbundling failed, reason 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_ErrorMessage4 {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_ErrorMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unbundling success, to bind pages can rebind 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_ErrorMessage5 {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_ErrorMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bind failed, reason 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_ErrorMessage6 {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_ErrorMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binding  successfully,view bind infomation 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_ErrorMessage7 {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_ErrorMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_IsDVIRDesc_No {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_IsDVIRDesc_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_IsDVIRDesc_Yes {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_IsDVIRDesc_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unbundling failure 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_UnBindError {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_UnBindError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unbundling 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_btnLoginOut {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_btnLoginOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether has DVIR 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_HasDVIR {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_HasDVIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job content1 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_JobContent1 {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_JobContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job content2 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_JobContent2 {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_JobContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binding 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_Login_btnLogin {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_Login_btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether has DVIR 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_Login_HasDVIR {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_Login_HasDVIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job content1 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_Login_JobContent1 {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_Login_JobContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job content2 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_Login_JobContent2 {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_Login_JobContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binding 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_Login_Title {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_Login_UserName {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_Login_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login information 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_Title {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_UserName {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select job content1 的本地化字符串。
        /// </summary>
        public static string LoginCenter_JS_Login_ErrorMessage1 {
            get {
                return ResourceManager.GetString("LoginCenter_JS_Login_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select job content2 的本地化字符串。
        /// </summary>
        public static string LoginCenter_JS_Login_ErrorMessage2 {
            get {
                return ResourceManager.GetString("LoginCenter_JS_Login_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Handle failure, reason 的本地化字符串。
        /// </summary>
        public static string Monitor_Controller_ErrorMessage1 {
            get {
                return ResourceManager.GetString("Monitor_Controller_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown barcode handle success 的本地化字符串。
        /// </summary>
        public static string Monitor_Controller_SuccessMessage1 {
            get {
                return ResourceManager.GetString("Monitor_Controller_SuccessMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Division number handle success 的本地化字符串。
        /// </summary>
        public static string Monitor_Controller_SuccessMessage2 {
            get {
                return ResourceManager.GetString("Monitor_Controller_SuccessMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Part No. handle success 的本地化字符串。
        /// </summary>
        public static string Monitor_Controller_SuccessMessage3 {
            get {
                return ResourceManager.GetString("Monitor_Controller_SuccessMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bag number handle success 的本地化字符串。
        /// </summary>
        public static string Monitor_Controller_SuccessMessage4 {
            get {
                return ResourceManager.GetString("Monitor_Controller_SuccessMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Divide the number of log information 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Controller_ExcelName {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Controller_ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_btnDele {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_btnDele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export(Excel) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_btnExcel {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_btnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reverse select 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_btnInverseSele {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_btnInverseSele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print(PDF) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_btnPrint {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_btnQuery {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_btnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All select 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_btnSeleAll {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_btnSeleAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date of operation 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_Label1 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user name 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_Label2 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_menuButtonReport {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_menuButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Branch number of log infomation 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_Title {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure the log information to delete the selected? 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;center&gt; select the need to delete the data &lt;/center&gt; 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User number 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_Field1 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_Field2 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job content1 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_Field3 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 job content2 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_Field4 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_Field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gate way 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_Field5 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_Field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_Field6 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_Field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_Field7 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_Field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete log failed, reason 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Controller_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_HU_Controller_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete log success 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Controller_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_HU_Controller_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete the log failure 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Controller_ErrorMessage3 {
            get {
                return ResourceManager.GetString("OperationLog_HU_Controller_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bag number log information 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Controller_ExcelName {
            get {
                return ResourceManager.GetString("OperationLog_HU_Controller_ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_btnDele {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_btnDele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export(Excel) 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_btnExcel {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_btnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reverse select 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_btnInverseSele {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_btnInverseSele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print(PDF) 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_btnPrint {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_btnQuery {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_btnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All select 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_btnSeleAll {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_btnSeleAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date of operation 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_Label1 {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_Label2 {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_menuButtonReport {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_menuButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure the log information to delete the selected? 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;center&gt; select the need to delete the data &lt;/center&gt; 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User number 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_Field1 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_Field2 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job content1 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_Field3 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job content2 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_Field4 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_Field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gate way 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_Field5 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_Field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_Field6 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_Field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_Field7 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_Field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_btnDele {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_btnDele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export(Excel) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_btnExcel {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_btnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reverse select 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_btnInverseSele {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_btnInverseSele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print(PDF) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_btnPrint {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_btnQuery {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_btnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All select 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_btnSeleAll {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_btnSeleAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date of operation 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_Label1 {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_Label2 {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_menuButtonReport {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_menuButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login logout log 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_Title {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure the log information to delete the selected? 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;center&gt; select the need to delete the data &lt;/center&gt; 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User number 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_Field1 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_Field2 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job content1 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_Field3 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job content2 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_Field4 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_Field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gate way 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_Field5 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_Field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_Field6 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_Field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_Field7 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_Field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete log failed, reason 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Controller_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_Other_Controller_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete log success 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Controller_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_Other_Controller_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete the log failure 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Controller_ErrorMessage3 {
            get {
                return ResourceManager.GetString("OperationLog_Other_Controller_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other log information 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Controller_ExcelName {
            get {
                return ResourceManager.GetString("OperationLog_Other_Controller_ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_btnDele {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_btnDele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export(Excel) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_btnExcel {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_btnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reverse select 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_btnInverseSele {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_btnInverseSele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print(PDF) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_btnPrint {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_btnQuery {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_btnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All select 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_btnSeleAll {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_btnSeleAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date of operation 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_Label1 {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_Label2 {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_menuButtonReport {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_menuButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other log information 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_Title {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure the log information to delete the selected? 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;center&gt; select the need to delete the data &lt;/center&gt; 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User number 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_Field1 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_Field2 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job content1 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_Field3 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job content2 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_Field4 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_Field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gate way 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_Field5 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_Field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_Field6 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_Field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_Field7 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_Field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete log failed, reason 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Controller_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Controller_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete log success 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Controller_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Controller_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete the log failure 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Controller_ErrorMessage3 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Controller_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of the log information 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Controller_ExcelName {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Controller_ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_btnDele {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_btnDele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export(Excel) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_btnExcel {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_btnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reverse select 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_btnInverseSele {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_btnInverseSele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print(PDF) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_btnPrint {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_btnQuery {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_btnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All select 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_btnSeleAll {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_btnSeleAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date of operation 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_Label1 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_Label2 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Report 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_menuButtonReport {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_menuButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Divide the number of log information management 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_Title {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure the log information to delete the selected? 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;center&gt; select the need to delete the data &lt;/center&gt; 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User number 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_Field1 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_Field2 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job content1 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_Field3 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job content2 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_Field4 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_Field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gate way 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_Field5 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_Field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_Field6 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_Field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_Field7 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_Field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete log failed, reason 的本地化字符串。
        /// </summary>
        public static string Public_Controller_ErrorMessage1 {
            get {
                return ResourceManager.GetString("Public_Controller_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete log success 的本地化字符串。
        /// </summary>
        public static string Public_Controller_ErrorMessage2 {
            get {
                return ResourceManager.GetString("Public_Controller_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete the log failure 的本地化字符串。
        /// </summary>
        public static string Public_Controller_ErrorMessage3 {
            get {
                return ResourceManager.GetString("Public_Controller_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to logout? 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_AskForExit {
            get {
                return ResourceManager.GetString("Public_Dialog_AskForExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_ButtonOfClose {
            get {
                return ResourceManager.GetString("Public_Dialog_ButtonOfClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_ButtonOfPrint {
            get {
                return ResourceManager.GetString("Public_Dialog_ButtonOfPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_ButtonOfSave {
            get {
                return ResourceManager.GetString("Public_Dialog_ButtonOfSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No data, can not be export 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_NoDataForExcel {
            get {
                return ResourceManager.GetString("Public_Dialog_NoDataForExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No data, can not to print 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_NoDataForPrint {
            get {
                return ResourceManager.GetString("Public_Dialog_NoDataForPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the data to print 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_NoDataSelectForPrint {
            get {
                return ResourceManager.GetString("Public_Dialog_NoDataSelectForPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_Title {
            get {
                return ResourceManager.GetString("Public_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job scan log 的本地化字符串。
        /// </summary>
        public static string Public_LogType_1 {
            get {
                return ResourceManager.GetString("Public_LogType_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login log 的本地化字符串。
        /// </summary>
        public static string Public_LogType_2 {
            get {
                return ResourceManager.GetString("Public_LogType_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout log 的本地化字符串。
        /// </summary>
        public static string Public_LogType_3 {
            get {
                return ResourceManager.GetString("Public_LogType_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Public_Message_OK {
            get {
                return ResourceManager.GetString("Public_Message_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ---Please select--- 的本地化字符串。
        /// </summary>
        public static string Public_Select_DefaultItem {
            get {
                return ResourceManager.GetString("Public_Select_DefaultItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Male 的本地化字符串。
        /// </summary>
        public static string Public_Select_Sex_Man {
            get {
                return ResourceManager.GetString("Public_Select_Sex_Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Female 的本地化字符串。
        /// </summary>
        public static string Public_Select_Sex_Woman {
            get {
                return ResourceManager.GetString("Public_Select_Sex_Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This user number is already in use 的本地化字符串。
        /// </summary>
        public static string User_Controller_ErrorMessage1 {
            get {
                return ResourceManager.GetString("User_Controller_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete user information failed, reason 的本地化字符串。
        /// </summary>
        public static string User_Controller_ErrorMessage2 {
            get {
                return ResourceManager.GetString("User_Controller_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete user information success 的本地化字符串。
        /// </summary>
        public static string User_Controller_ErrorMessage3 {
            get {
                return ResourceManager.GetString("User_Controller_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete user information failed 的本地化字符串。
        /// </summary>
        public static string User_Controller_ErrorMessage4 {
            get {
                return ResourceManager.GetString("User_Controller_ErrorMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The system user information 的本地化字符串。
        /// </summary>
        public static string User_Controller_ExcelName {
            get {
                return ResourceManager.GetString("User_Controller_ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add the system user information 的本地化字符串。
        /// </summary>
        public static string User_Dialog_AddUser_Title {
            get {
                return ResourceManager.GetString("User_Dialog_AddUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify the system user information 的本地化字符串。
        /// </summary>
        public static string User_Dialog_UpdateUser_Title {
            get {
                return ResourceManager.GetString("User_Dialog_UpdateUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User number 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label1 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gate way 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label10 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remarks 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label11 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User password 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label2 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm password 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label3 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label4 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gender 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label5 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Old 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label6 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Staff number 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label7 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Staff department 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label8 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Staff position 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label9 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User number 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label1 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gate way 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label10 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remarks 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label11 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User password 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label2 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm password 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label3 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label4 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gender 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label5 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Old 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label6 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Staff number 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label7 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Staff department 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label8 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Staff position 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label9 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The system user information management 的本地化字符串。
        /// </summary>
        public static string User_Html_Title {
            get {
                return ResourceManager.GetString("User_Html_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User number 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field1 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field2 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gender 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field3 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Old 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field4 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Staff number 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field5 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Staff departments 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field6 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Staff positions 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field7 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gate way 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field8 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field9 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool1 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool2 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool3 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool4 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All select 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool5 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reverse select 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool6 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool7 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print barcode 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool8 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool9 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please complete the information &lt;br/&gt; (user number, password, confirm the password, gate way) 的本地化字符串。
        /// </summary>
        public static string User_JS_ErrorMessage1 {
            get {
                return ResourceManager.GetString("User_JS_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The password and confirm password do not match 的本地化字符串。
        /// </summary>
        public static string User_JS_ErrorMessage2 {
            get {
                return ResourceManager.GetString("User_JS_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The maximum length of the user name is 10, and is a letter or a number or a combination thereof 的本地化字符串。
        /// </summary>
        public static string User_JS_ErrorMessage3 {
            get {
                return ResourceManager.GetString("User_JS_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;center&gt; select modify data (can only select one line) &lt;/center&gt; 的本地化字符串。
        /// </summary>
        public static string User_JS_ErrorMessage4 {
            get {
                return ResourceManager.GetString("User_JS_ErrorMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure need the system user information to delete the selected it 的本地化字符串。
        /// </summary>
        public static string User_JS_ErrorMessage5 {
            get {
                return ResourceManager.GetString("User_JS_ErrorMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;center&gt; select the need to delete the data &lt;/center&gt; 的本地化字符串。
        /// </summary>
        public static string User_JS_ErrorMessage6 {
            get {
                return ResourceManager.GetString("User_JS_ErrorMessage6", resourceCulture);
            }
        }
    }
}
