//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelServiceSys.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabelServiceSys.Resources.zh-CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 分 单 号 日 志 表 的本地化字符串。
        /// </summary>
        public static string Default_Html_btnOperationLog_Hawb {
            get {
                return ResourceManager.GetString("Default_Html_btnOperationLog_Hawb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 袋 号 日 志 表 的本地化字符串。
        /// </summary>
        public static string Default_Html_btnOperationLog_HU {
            get {
                return ResourceManager.GetString("Default_Html_btnOperationLog_HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登 陆 登 出 日 志 的本地化字符串。
        /// </summary>
        public static string Default_Html_btnOperationLog_Login {
            get {
                return ResourceManager.GetString("Default_Html_btnOperationLog_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其 他 日 志 信 息 的本地化字符串。
        /// </summary>
        public static string Default_Html_btnOperationLog_Other {
            get {
                return ResourceManager.GetString("Default_Html_btnOperationLog_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 件 号 日 志 表 的本地化字符串。
        /// </summary>
        public static string Default_Html_btnOperationLog_Pcid {
            get {
                return ResourceManager.GetString("Default_Html_btnOperationLog_Pcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用 户 信 息 管 理 的本地化字符串。
        /// </summary>
        public static string Default_Html_btnUserManagement {
            get {
                return ResourceManager.GetString("Default_Html_btnUserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前登录 的本地化字符串。
        /// </summary>
        public static string Default_Html_CurrentUser {
            get {
                return ResourceManager.GetString("Default_Html_CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        public static string Default_Html_Exit {
            get {
                return ResourceManager.GetString("Default_Html_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台工作区 的本地化字符串。
        /// </summary>
        public static string Default_Html_LeftNavigation_Title {
            get {
                return ResourceManager.GetString("Default_Html_LeftNavigation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string Default_Html_mm_exit {
            get {
                return ResourceManager.GetString("Default_Html_mm_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Default_Html_mm_tabclose {
            get {
                return ResourceManager.GetString("Default_Html_mm_tabclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部关闭 的本地化字符串。
        /// </summary>
        public static string Default_Html_mm_tabcloseall {
            get {
                return ResourceManager.GetString("Default_Html_mm_tabcloseall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前页左侧全部关闭 的本地化字符串。
        /// </summary>
        public static string Default_Html_mm_tabcloseleft {
            get {
                return ResourceManager.GetString("Default_Html_mm_tabcloseleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭其他 的本地化字符串。
        /// </summary>
        public static string Default_Html_mm_tabcloseother {
            get {
                return ResourceManager.GetString("Default_Html_mm_tabcloseother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前页右侧全部关闭 的本地化字符串。
        /// </summary>
        public static string Default_Html_mm_tabcloseright {
            get {
                return ResourceManager.GetString("Default_Html_mm_tabcloseright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Default_Html_mm_tabupdate {
            get {
                return ResourceManager.GetString("Default_Html_mm_tabupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用指南 的本地化字符串。
        /// </summary>
        public static string Default_Html_tab_Content_1 {
            get {
                return ResourceManager.GetString("Default_Html_tab_Content_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绩效考核系统 的本地化字符串。
        /// </summary>
        public static string Default_Html_Title {
            get {
                return ResourceManager.GetString("Default_Html_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用指南 的本地化字符串。
        /// </summary>
        public static string Default_JS_defaultTabTitle {
            get {
                return ResourceManager.GetString("Default_JS_defaultTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误原因 的本地化字符串。
        /// </summary>
        public static string Error_Html_Label1 {
            get {
                return ResourceManager.GetString("Error_Html_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回登录页 的本地化字符串。
        /// </summary>
        public static string Error_Html_Label2 {
            get {
                return ResourceManager.GetString("Error_Html_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出错啦！！！ 的本地化字符串。
        /// </summary>
        public static string Error_Html_Title {
            get {
                return ResourceManager.GetString("Error_Html_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未指定设备类型 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_ErrorMessage1 {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未指定是否有DVIR 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_ErrorMessage2 {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未指定用户名 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_ErrorMessage3 {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解绑失败,原因 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_ErrorMessage4 {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_ErrorMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解绑成功,转入绑定页可重新绑定 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_ErrorMessage5 {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_ErrorMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定失败,原因 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_ErrorMessage6 {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_ErrorMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定成功,查看绑定信息 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_ErrorMessage7 {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_ErrorMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_IsDVIRDesc_No {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_IsDVIRDesc_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_IsDVIRDesc_Yes {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_IsDVIRDesc_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解绑失败 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Controller_UnBindError {
            get {
                return ResourceManager.GetString("LoginCenter_Controller_UnBindError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解绑 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_btnLoginOut {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_btnLoginOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有无DVIR 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_HasDVIR {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_HasDVIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一级工作内容 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_JobContent1 {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_JobContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级工作内容 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_JobContent2 {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_JobContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_Login_btnLogin {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_Login_btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有无DVIR 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_Login_HasDVIR {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_Login_HasDVIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一级工作内容 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_Login_JobContent1 {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_Login_JobContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级工作内容 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_Login_JobContent2 {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_Login_JobContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_Login_Title {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_Login_UserName {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_Login_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录信息 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_Title {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string LoginCenter_Html_Index_UserName {
            get {
                return ResourceManager.GetString("LoginCenter_Html_Index_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一级工作内容 的本地化字符串。
        /// </summary>
        public static string LoginCenter_JS_Login_ErrorMessage1 {
            get {
                return ResourceManager.GetString("LoginCenter_JS_Login_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择二级工作内容 的本地化字符串。
        /// </summary>
        public static string LoginCenter_JS_Login_ErrorMessage2 {
            get {
                return ResourceManager.GetString("LoginCenter_JS_Login_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理失败,原因 的本地化字符串。
        /// </summary>
        public static string Monitor_Controller_ErrorMessage1 {
            get {
                return ResourceManager.GetString("Monitor_Controller_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知条码处理成功 的本地化字符串。
        /// </summary>
        public static string Monitor_Controller_SuccessMessage1 {
            get {
                return ResourceManager.GetString("Monitor_Controller_SuccessMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分单号处理成功 的本地化字符串。
        /// </summary>
        public static string Monitor_Controller_SuccessMessage2 {
            get {
                return ResourceManager.GetString("Monitor_Controller_SuccessMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 件号处理成功 的本地化字符串。
        /// </summary>
        public static string Monitor_Controller_SuccessMessage3 {
            get {
                return ResourceManager.GetString("Monitor_Controller_SuccessMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 袋号处理成功 的本地化字符串。
        /// </summary>
        public static string Monitor_Controller_SuccessMessage4 {
            get {
                return ResourceManager.GetString("Monitor_Controller_SuccessMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分单号日志信息 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Controller_ExcelName {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Controller_ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_btnDele {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_btnDele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出(Excel) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_btnExcel {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_btnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反选 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_btnInverseSele {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_btnInverseSele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印(PDF) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_btnPrint {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_btnQuery {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_btnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_btnSeleAll {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_btnSeleAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作日期 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_Label1 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_Label2 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_menuButtonReport {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_menuButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分单号日志信息管理 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_Html_Title {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_Html_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定需要删除所选的操作日志信息吗？ 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;center&gt;请选择需要删除的数据&lt;/center&gt; 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户号 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_Field1 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_Field2 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一级工作流程 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_Field3 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级工作流程 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_Field4 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_Field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 口岸代码 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_Field5 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_Field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作时间 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_Field6 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_Field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作内容 的本地化字符串。
        /// </summary>
        public static string OperationLog_Hawb_JS_Field7 {
            get {
                return ResourceManager.GetString("OperationLog_Hawb_JS_Field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除日志失败，原因 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Controller_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_HU_Controller_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除日志成功 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Controller_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_HU_Controller_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除日志失败 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Controller_ErrorMessage3 {
            get {
                return ResourceManager.GetString("OperationLog_HU_Controller_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 袋号日志信息 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Controller_ExcelName {
            get {
                return ResourceManager.GetString("OperationLog_HU_Controller_ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_btnDele {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_btnDele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出(Excel) 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_btnExcel {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_btnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反选 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_btnInverseSele {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_btnInverseSele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印(PDF) 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_btnPrint {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_btnQuery {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_btnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_btnSeleAll {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_btnSeleAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作日期 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_Label1 {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_Label2 {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_Html_menuButtonReport {
            get {
                return ResourceManager.GetString("OperationLog_HU_Html_menuButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定需要删除所选的操作日志信息吗？ 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;center&gt;请选择需要删除的数据&lt;/center&gt; 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户号 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_Field1 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_Field2 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一级工作流程 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_Field3 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级工作流程 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_Field4 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_Field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 口岸代码 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_Field5 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_Field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作时间 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_Field6 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_Field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作内容 的本地化字符串。
        /// </summary>
        public static string OperationLog_HU_JS_Field7 {
            get {
                return ResourceManager.GetString("OperationLog_HU_JS_Field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_btnDele {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_btnDele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出(Excel) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_btnExcel {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_btnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反选 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_btnInverseSele {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_btnInverseSele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印(PDF) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_btnPrint {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_btnQuery {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_btnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_btnSeleAll {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_btnSeleAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作日期 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_Label1 {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_Label2 {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_menuButtonReport {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_menuButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登入登出日志 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_Html_Title {
            get {
                return ResourceManager.GetString("OperationLog_Login_Html_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定需要删除所选的操作日志信息吗？ 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;center&gt;请选择需要删除的数据&lt;/center&gt; 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户号 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_Field1 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_Field2 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一级工作流程 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_Field3 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级工作流程 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_Field4 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_Field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 口岸代码 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_Field5 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_Field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作时间 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_Field6 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_Field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作内容 的本地化字符串。
        /// </summary>
        public static string OperationLog_Login_JS_Field7 {
            get {
                return ResourceManager.GetString("OperationLog_Login_JS_Field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除日志失败，原因 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Controller_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_Other_Controller_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除日志成功 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Controller_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_Other_Controller_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除日志失败 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Controller_ErrorMessage3 {
            get {
                return ResourceManager.GetString("OperationLog_Other_Controller_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他日志信息 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Controller_ExcelName {
            get {
                return ResourceManager.GetString("OperationLog_Other_Controller_ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_btnDele {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_btnDele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出(Excel) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_btnExcel {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_btnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反选 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_btnInverseSele {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_btnInverseSele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印(PDF) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_btnPrint {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_btnQuery {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_btnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_btnSeleAll {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_btnSeleAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作日期 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_Label1 {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_Label2 {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_menuButtonReport {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_menuButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他日志信息 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_Html_Title {
            get {
                return ResourceManager.GetString("OperationLog_Other_Html_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定需要删除所选的操作日志信息吗？ 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;center&gt;请选择需要删除的数据&lt;/center&gt; 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户号 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_Field1 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_Field2 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一级工作流程 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_Field3 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级工作流程 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_Field4 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_Field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 口岸代码 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_Field5 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_Field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作时间 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_Field6 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_Field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作内容 的本地化字符串。
        /// </summary>
        public static string OperationLog_Other_JS_Field7 {
            get {
                return ResourceManager.GetString("OperationLog_Other_JS_Field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除日志失败，原因 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Controller_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Controller_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除日志成功 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Controller_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Controller_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除日志失败 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Controller_ErrorMessage3 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Controller_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 件号日志信息 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Controller_ExcelName {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Controller_ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_btnDele {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_btnDele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出(Excel) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_btnExcel {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_btnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反选 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_btnInverseSele {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_btnInverseSele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印(PDF) 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_btnPrint {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_btnQuery {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_btnQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_btnSeleAll {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_btnSeleAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作日期 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_Label1 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_Label2 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_menuButtonReport {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_menuButtonReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分单号日志信息管理 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_Html_Title {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_Html_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定需要删除所选的操作日志信息吗？ 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_ErrorMessage1 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;center&gt;请选择需要删除的数据&lt;/center&gt; 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_ErrorMessage2 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户号 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_Field1 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_Field2 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一级工作流程 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_Field3 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级工作流程 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_Field4 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_Field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 口岸代码 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_Field5 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_Field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作时间 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_Field6 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_Field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作内容 的本地化字符串。
        /// </summary>
        public static string OperationLog_Pcid_JS_Field7 {
            get {
                return ResourceManager.GetString("OperationLog_Pcid_JS_Field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除日志失败，原因 的本地化字符串。
        /// </summary>
        public static string Public_Controller_ErrorMessage1 {
            get {
                return ResourceManager.GetString("Public_Controller_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除日志成功 的本地化字符串。
        /// </summary>
        public static string Public_Controller_ErrorMessage2 {
            get {
                return ResourceManager.GetString("Public_Controller_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除日志失败 的本地化字符串。
        /// </summary>
        public static string Public_Controller_ErrorMessage3 {
            get {
                return ResourceManager.GetString("Public_Controller_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定需要注销吗？ 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_AskForExit {
            get {
                return ResourceManager.GetString("Public_Dialog_AskForExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_ButtonOfClose {
            get {
                return ResourceManager.GetString("Public_Dialog_ButtonOfClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_ButtonOfPrint {
            get {
                return ResourceManager.GetString("Public_Dialog_ButtonOfPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_ButtonOfSave {
            get {
                return ResourceManager.GetString("Public_Dialog_ButtonOfSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有数据，不可导出 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_NoDataForExcel {
            get {
                return ResourceManager.GetString("Public_Dialog_NoDataForExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有数据，不可打印 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_NoDataForPrint {
            get {
                return ResourceManager.GetString("Public_Dialog_NoDataForPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择需要打印的数据 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_NoDataSelectForPrint {
            get {
                return ResourceManager.GetString("Public_Dialog_NoDataSelectForPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示信息 的本地化字符串。
        /// </summary>
        public static string Public_Dialog_Title {
            get {
                return ResourceManager.GetString("Public_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作业扫描日志 的本地化字符串。
        /// </summary>
        public static string Public_LogType_1 {
            get {
                return ResourceManager.GetString("Public_LogType_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录日志 的本地化字符串。
        /// </summary>
        public static string Public_LogType_2 {
            get {
                return ResourceManager.GetString("Public_LogType_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登出日志 的本地化字符串。
        /// </summary>
        public static string Public_LogType_3 {
            get {
                return ResourceManager.GetString("Public_LogType_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Public_Message_OK {
            get {
                return ResourceManager.GetString("Public_Message_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ---请选择--- 的本地化字符串。
        /// </summary>
        public static string Public_Select_DefaultItem {
            get {
                return ResourceManager.GetString("Public_Select_DefaultItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 男 的本地化字符串。
        /// </summary>
        public static string Public_Select_Sex_Man {
            get {
                return ResourceManager.GetString("Public_Select_Sex_Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 女 的本地化字符串。
        /// </summary>
        public static string Public_Select_Sex_Woman {
            get {
                return ResourceManager.GetString("Public_Select_Sex_Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此用户号已经使用 的本地化字符串。
        /// </summary>
        public static string User_Controller_ErrorMessage1 {
            get {
                return ResourceManager.GetString("User_Controller_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除用户信息失败，原因 的本地化字符串。
        /// </summary>
        public static string User_Controller_ErrorMessage2 {
            get {
                return ResourceManager.GetString("User_Controller_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除用户信息成功 的本地化字符串。
        /// </summary>
        public static string User_Controller_ErrorMessage3 {
            get {
                return ResourceManager.GetString("User_Controller_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除用户信息失败 的本地化字符串。
        /// </summary>
        public static string User_Controller_ErrorMessage4 {
            get {
                return ResourceManager.GetString("User_Controller_ErrorMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统用户信息 的本地化字符串。
        /// </summary>
        public static string User_Controller_ExcelName {
            get {
                return ResourceManager.GetString("User_Controller_ExcelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加系统用户信息 的本地化字符串。
        /// </summary>
        public static string User_Dialog_AddUser_Title {
            get {
                return ResourceManager.GetString("User_Dialog_AddUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改系统用户信息 的本地化字符串。
        /// </summary>
        public static string User_Dialog_UpdateUser_Title {
            get {
                return ResourceManager.GetString("User_Dialog_UpdateUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户号 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label1 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 口岸代码 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label10 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label11 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label2 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label3 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label4 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label5 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年龄 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label6 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工工号 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label7 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户部门 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label8 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户职位 的本地化字符串。
        /// </summary>
        public static string User_Html_Create_Label9 {
            get {
                return ResourceManager.GetString("User_Html_Create_Label9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户号 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label1 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 口岸代码 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label10 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label11 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label2 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label3 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label4 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label5 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年龄 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label6 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工工号 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label7 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户部门 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label8 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户职位 的本地化字符串。
        /// </summary>
        public static string User_Html_Edit_Label9 {
            get {
                return ResourceManager.GetString("User_Html_Edit_Label9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统用户信息管理 的本地化字符串。
        /// </summary>
        public static string User_Html_Title {
            get {
                return ResourceManager.GetString("User_Html_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户号 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field1 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户姓名 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field2 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field3 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年龄 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field4 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工工号 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field5 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工部门 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field6 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工职位 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field7 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 口岸代码 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field8 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Field9 {
            get {
                return ResourceManager.GetString("User_JS_DG_Field9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool1 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool2 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool3 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool4 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool5 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反选 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool6 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool7 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印条码 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool8 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string User_JS_DG_Tool9 {
            get {
                return ResourceManager.GetString("User_JS_DG_Tool9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写完整信息&lt;br/&gt;(用户号、密码、确认密码、口岸) 的本地化字符串。
        /// </summary>
        public static string User_JS_ErrorMessage1 {
            get {
                return ResourceManager.GetString("User_JS_ErrorMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码与确认密码不一致 的本地化字符串。
        /// </summary>
        public static string User_JS_ErrorMessage2 {
            get {
                return ResourceManager.GetString("User_JS_ErrorMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名最大长度为10,且为字母或数字或其组合 的本地化字符串。
        /// </summary>
        public static string User_JS_ErrorMessage3 {
            get {
                return ResourceManager.GetString("User_JS_ErrorMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;center&gt;请选择数据进行修改(只可选择一行)&lt;/center&gt; 的本地化字符串。
        /// </summary>
        public static string User_JS_ErrorMessage4 {
            get {
                return ResourceManager.GetString("User_JS_ErrorMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定需要删除所选的系统用户信息吗 的本地化字符串。
        /// </summary>
        public static string User_JS_ErrorMessage5 {
            get {
                return ResourceManager.GetString("User_JS_ErrorMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;center&gt;请选择需要删除的数据&lt;/center&gt; 的本地化字符串。
        /// </summary>
        public static string User_JS_ErrorMessage6 {
            get {
                return ResourceManager.GetString("User_JS_ErrorMessage6", resourceCulture);
            }
        }
    }
}
